-- Seed: schools
insert into public.schools (id, name, province, district) values
  (gen_random_uuid(), 'Soweto High School', 'Gauteng', 'Johannesburg South'),
  (gen_random_uuid(), 'Khayelitsha Secondary School', 'Western Cape', 'Metro South'),
  (gen_random_uuid(), 'Umlazi Comprehensive School', 'KwaZulu-Natal', 'Umlazi'),
  (gen_random_uuid(), 'Mthatha High School', 'Eastern Cape', 'OR Tambo'),
  (gen_random_uuid(), 'Polokwane Secondary School', 'Limpopo', 'Capricorn'),
  (gen_random_uuid(), 'Mbombela High School', 'Mpumalanga', 'Ehlanzeni'),
  (gen_random_uuid(), 'Rustenburg Secondary School', 'North West', 'Bojanala'),
  (gen_random_uuid(), 'Bloemfontein High School', 'Free State', 'Mangaung'),
  (gen_random_uuid(), 'Kimberley Secondary School', 'Northern Cape', 'Frances Baard');

-- Seed: 12 MVP lessons (published, system-contributed — contributor_id is
-- intentionally null since these predate any real teacher signup)
insert into public.lessons (title, description, pillar, grade_min, grade_max, objectives, resource_name, resource_type, activity, discussion_question, duration_minutes, contributor_name, contributor_role, avatar_id, color, sponsor, status, views, completions, published_at) values
  ('Discover Your Strengths & Talents', 'Everyone has natural strengths — this lesson helps you find yours and start connecting them to real career paths.', 'career', 7, 9, array['Identify 3 personal strengths using a simple self-assessment', 'Understand the difference between a skill and a talent', 'Connect your strengths to at least 2 possible career paths', 'Set one small goal to develop a strength further'], 'Strengths Finder Worksheet', 'PDF', 'List 5 things people say you''re good at, then circle the one you want to grow this term.', 'What is one strength you have that surprised you when you really thought about it?', 9, 'Thabo Nkosi', 'Career Counsellor', 'thabo', '#FF8A00', null, 'published', 2581, 605, now()),
  ('Subject Choices → Career Pathways', 'Your subject choices shape your options after school. Learn how to map them to university, TVET and entrepreneurship pathways.', 'career', 10, 12, array['Understand how school subjects link to career fields', 'Compare university, TVET college and entrepreneurship routes', 'Learn what APS scores are and how they work', 'Draft a shortlist of 3 possible pathways for yourself'], 'Subject-to-Career Pathway Map', 'PDF', 'Build a one-page pathway plan showing your current subjects and where they could lead.', 'Which career pathway are you most curious about right now, and why?', 12, 'Thabo Nkosi', 'Career Counsellor', 'thabo', '#FF8A00', null, 'published', 3608, 175, now()),
  ('Money Basics: Save, Spend, Grow', 'A friendly introduction to needs vs wants, saving and how money can grow over time.', 'finance', 7, 9, array['Tell the difference between a need and a want', 'Explain why saving even small amounts matters', 'Set a simple savings goal', 'Understand what a bank account is for'], 'My First Savings Tracker', 'PDF', 'Track everything you spend for one week and sort it into needs vs wants.', 'What is one thing you''re saving up for right now?', 8, 'Zanele Petersen', 'Financial Educator, Standard Bank', 'zanele', '#F4B84C', 'Standard Bank', 'published', 2804, 659, now()),
  ('Credit, Debt & Building Wealth', 'Understand how credit and debt really work, and what it takes to start building wealth for your future.', 'finance', 10, 12, array['Explain how credit and interest work', 'Identify the difference between good debt and bad debt', 'Understand the basics of investing over time', 'Build a simple monthly budget'], 'R500 Monthly Budget Template', 'PDF', 'Create your own R500 monthly budget, splitting it across needs, wants and savings.', 'What is one money habit you want to build before you turn 21?', 14, 'Zanele Petersen', 'Financial Educator, Standard Bank', 'zanele', '#F4B84C', 'Standard Bank', 'published', 3047, 937, now()),
  ('Stay Safe Online', 'Practical ways to protect your privacy, spot scams and stay in control of your digital footprint.', 'digital', 7, 9, array['Recognise 3 common online safety risks', 'Understand what a digital footprint is', 'Learn how to set strong privacy settings', 'Know what to do if something online feels unsafe'], 'Online Safety Checklist', 'PDF', 'Review the privacy settings on one app you use and tighten at least 2 of them.', 'What would you do if a stranger online asked for your personal details?', 7, 'Sipho Mthembu', 'Tech Educator', 'sipho', '#006E68', null, 'published', 1903, 441, now()),
  ('Your Digital Brand & AI Awareness', 'What you post shapes how the world sees you. Learn to build a strong personal brand and understand how AI is changing media.', 'digital', 10, 12, array['Audit your current online presence', 'Learn what makes a strong personal brand', 'Understand the basics of how AI-generated content works', 'Spot AI-generated or misleading content'], 'Personal Brand Audit Guide', 'PDF', 'Write a 3-line bio that represents who you want to be seen as online.', 'How has AI already changed the way you use the internet?', 11, 'Sipho Mthembu', 'Tech Educator', 'sipho', '#006E68', null, 'published', 4201, 500, now()),
  ('What Problem Can You Solve?', 'Every business starts with a problem worth solving. Learn how to spot problems around you worth acting on.', 'entrepreneurship', 7, 9, array['Understand what "entrepreneurship" really means', 'Practise spotting everyday problems', 'Turn a problem into a simple idea', 'Share an idea clearly in one sentence'], 'Problem Spotting Worksheet', 'PDF', 'Write down 3 problems you notice in your school or community this week.', 'What''s one everyday problem you wish someone would fix?', 8, 'Kagiso Dlamini', 'Founder, YouthHustle SA', 'kagiso', '#E8603C', null, 'published', 1448, 625, now()),
  ('Build a Simple Business Model', 'Turn an idea into a real plan. Learn pricing, marketing basics and how to pitch with confidence.', 'entrepreneurship', 10, 12, array['Map out who your customer is', 'Understand basic pricing and costs', 'Learn the fundamentals of marketing an idea', 'Structure a 60-second pitch'], 'One-Page Business Model Canvas', 'PDF', 'Fill out a one-page business model canvas for an idea of your own.', 'What business would you start tomorrow if money wasn''t a barrier?', 13, 'Kagiso Dlamini', 'Founder, YouthHustle SA', 'kagiso', '#E8603C', null, 'published', 509, 136, now()),
  ('Confidence & Public Speaking Basics', 'Build the confidence to speak up in class, in groups and in your community.', 'leadership', 7, 9, array['Learn 3 simple techniques to calm nerves before speaking', 'Practise structuring a short talk', 'Understand the role of body language', 'Build confidence through small daily practice'], 'Confidence Building Guide', 'PDF', 'Record a 30-second video introducing yourself and one thing you''re proud of.', 'When was the last time you felt proud of speaking up?', 7, 'Amahle Tshabalala', 'Youth Leadership Coach', 'amahle', '#0D665F', null, 'published', 3620, 775, now()),
  ('Leadership in Action', 'Real leadership is about action, not titles. Learn how to lead a team, resolve conflict and lead with purpose.', 'leadership', 10, 12, array['Understand different leadership styles', 'Practise basic conflict resolution', 'Learn how to motivate a team', 'Define your own sense of purpose'], 'Leading With Purpose Workbook', 'PDF', 'Describe a real situation where you could lead — and one first step you''d take.', 'Who is a leader you admire, and what makes them stand out?', 12, 'Amahle Tshabalala', 'Youth Leadership Coach', 'amahle', '#0D665F', null, 'published', 2671, 931, now()),
  ('Understanding Your Community', 'Explore what makes up your community, and the small actions that make a big difference.', 'civic', 7, 9, array['Identify the different groups that make up your community', 'Understand basic rights and responsibilities', 'Spot one local issue worth caring about', 'Learn what "active citizenship" means'], 'My Community Map', 'PDF', 'Draw or list the people, places and groups that make up your community.', 'What is one thing you love about your community, and one thing you''d change?', 8, 'Nomusa Molefe', 'Community Organiser', 'nomusa', '#5F9770', null, 'published', 3382, 62, now()),
  ('Active Citizenship & Youth Voice', 'Your voice counts. Learn how young people are driving real social impact across South Africa.', 'civic', 10, 12, array['Understand how civic participation works in South Africa', 'Explore real youth-led social impact projects', 'Learn how to start a small community initiative', 'Reflect on your own role as an active citizen'], 'Youth Voice Action Guide', 'PDF', 'Outline a small community project you could start with 3 friends.', 'What issue would you want to see more young people speak up about?', 11, 'Nomusa Molefe', 'Community Organiser', 'nomusa', '#5F9770', null, 'published', 3645, 321, now());

-- Seed: sponsor (Standard Bank sponsors the Financial Literacy pillar)
insert into public.sponsors (company_name, industry, description, sponsored_pillar) values
  ('Standard Bank', 'Banking & Financial Services', 'Powering financial literacy education for South African youth.', 'finance');
